// <auto-generated />
using System;
using Chat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chat.Migrations
{
    [DbContext(typeof(GameNetworkDbContext))]
    partial class GameNetworkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chat.Data.Entites.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("EarnedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Published your first game review",
                            EarnedOnDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "First Post",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Left 5+ comments",
                            EarnedOnDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Comment Master",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Specialized in Strategy games",
                            EarnedOnDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Strategy Expert",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Reviewed 3+ indie games",
                            EarnedOnDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Indie Explorer",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Created a post about automation or factory-building games",
                            EarnedOnDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Factory Overlord",
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Posted multiple FPS-related reviews",
                            EarnedOnDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "FPS Veteran",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Shared expert tips about tower defense games",
                            EarnedOnDate = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Tower Defense Guru",
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            Description = "Left helpful comments on 5 different posts",
                            EarnedOnDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Community Helper",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Chat.Data.Entites.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentTitle = "Congrats!",
                            Content = "Congrats on finishing The Witcher! That ending hits hard!",
                            IsDeleted = false,
                            PostId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CommentTitle = "Welcome!",
                            Content = "Welcome to the Cyberpunk fandom! The updates made the game so much better.",
                            IsDeleted = false,
                            PostId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CommentTitle = "I know!",
                            Content = "Civ VI is dangerously addictive. One more turn? More like 200.",
                            IsDeleted = false,
                            PostId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CommentTitle = "Factory black hole",
                            Content = "Satisfactory is basically a productivity black hole, but in a good way.",
                            IsDeleted = false,
                            PostId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CommentTitle = "Multiplayer",
                            Content = "COD multiplayer still slaps, even if the campaign is questionable.",
                            IsDeleted = false,
                            PostId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CommentTitle = "AFK Gang",
                            Content = "AFK meta in Bloons? Best gameplay.",
                            IsDeleted = false,
                            PostId = 6,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Chat.Data.Entites.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GameTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Just finished The Witcher 3! Amazing storyline!",
                            GameTitle = "The Witcher 3",
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "played the new Cyberpunk 2077 and the storyline and the game play is amazing!",
                            GameTitle = "Cyberpunk 2077",
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Civilization VI is consuming my life. One more turn!",
                            GameTitle = "Civilization VI",
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Huge congrats to Satisfactory for finally going global! I cannot wait to sink an irresponsible amount of time into this game and absolutely ruin my sleep schedule all over again. Here's to building factories so needlessly complicated that even future me will question my life choices. Let the chaos begin!",
                            GameTitle = "Satisfactory",
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "New COD game is bad compared to what they did with Battlefield 6!",
                            GameTitle = "Call of Duty",
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Bro, let's be real — the best hero in Bloons TD 6 is whoever lets me AFK the longest without the whole map exploding. Absolutely best strategy.",
                            GameTitle = "Bloons TD 6",
                            IsDeleted = false,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Chat.Data.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "pro@abv.bg",
                            IsDeleted = false,
                            UserName = "ProGamer2000"
                        },
                        new
                        {
                            Id = 2,
                            Email = "cyber@abv.bg",
                            IsDeleted = false,
                            UserName = "CyberWarrior"
                        },
                        new
                        {
                            Id = 3,
                            Email = "strategy@abv.bg",
                            IsDeleted = false,
                            UserName = "StrategyQueen"
                        },
                        new
                        {
                            Id = 4,
                            Email = "LetsGameItOut@gmail.com",
                            IsDeleted = false,
                            UserName = "LetsGameItOut"
                        },
                        new
                        {
                            Id = 5,
                            Email = "MaxLevelIdot@gmail.com",
                            IsDeleted = false,
                            UserName = "MaxLevelIdot"
                        });
                });

            modelBuilder.Entity("Chat.Data.Entites.Achievement", b =>
                {
                    b.HasOne("Chat.Data.Entites.User", "User")
                        .WithMany("AchievementsAndRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat.Data.Entites.Comment", b =>
                {
                    b.HasOne("Chat.Data.Entites.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat.Data.Entites.User", "User")
                        .WithMany("UserComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat.Data.Entites.Post", b =>
                {
                    b.HasOne("Chat.Data.Entites.User", "User")
                        .WithMany("UserPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat.Data.Entites.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Chat.Data.Entites.User", b =>
                {
                    b.Navigation("AchievementsAndRoles");

                    b.Navigation("UserComments");

                    b.Navigation("UserPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
